name: Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  security:
    name: Security
    uses: Advans-IT-Solutions-GmbH/.github/.github/workflows/reusable-security.yml@f7ecea52f37160773a230b6ef190cbe1466416f9 # v1
    with:
      fail_on_findings: false